[build.environment]
  NODE_VERSION = "20.x"

[build]
  publish = "apps/nisa-presentation/dist"
  command = "pnpm build:nisa-presentation"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
